version: 2
#orbs:
#  allure: ayte/allure@0.1.3
jobs:
  build:
    machine:
      #image: ubuntu-2204:2024.04.4
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    # Remove if parallelism is not desired
    # parallelism: 2
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - checkout
      - run: ./gradlew downloadAllure
      - run: ./gradlew clean test
      #- allure/report
      - run: ./gradlew allureReport

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/reports/allure-report

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
